### ISSUE TITLE
Getting "no resource plugin" when running pulumi from container

### ISSUE THREAD

**Issue by nicodeg87** [pulumi/pulumi-docker-containers#83] opened 2022-01-07 14:37 UTC
After running pulumi new  on an empty directory (aws-javascript project), when trying to do pulumi up/preview Im getting the following error:

`error: no resource plugin 'aws-v4.33.1' found in the workspace or on your $PATH, install the plugin using pulumi plugin install resource aws v4.33.1`

**Steps to reproduce:**

1. `mkdir /tmp/app && cd /tmp/app` 

2. Run pulumi new with oficial docker image:
`docker run -it \
    -e PULUMI_ACCESS_TOKEN \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -w /app \
    -v $(pwd):/app \
    pulumi/pulumi \
    new aws-javascript`

3. Run pulumi preview with docker:
`docker run -it \
    -e PULUMI_ACCESS_TOKEN \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -w /app \
    -v $(pwd):/app \
    pulumi/pulumi \
    preview `

**Expected result:**
We should get pulumi preview output.

**Actual result:**
We are getting error 
`Diagnostics:
  pulumi:providers:aws (default_4_33_1):
    error: no resource plugin 'aws-v4.33.1' found in the workspace or on your $PATH, install the plugin using pulumi plugin install resource aws v4.33.1`

**Comment by leezen** [comment] 2022-01-08 03:39
I'm not able to reproduce this locally:

```
❯ docker run -it -e PULUMI_ACCESS_TOKEN -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -w /app -v "$(pwd)":/app pulumi/pulumi pre
Logging in using access token from PULUMI_ACCESS_TOKEN
Please choose a stack, or create a new one: dev
Previewing update (dev)

View Live: https://app.pulumi.com/leezen/test-app/dev/previews/db0a7ecc-d2d0-4ba2-8241-d465958e89a1

[resource plugin docker-3.1.0] installing
Downloading plugin: 0 B / 16.68 MiB [----------------------------------]   0.00%[resource plugin aws-4.33.1] installing
Downloading plugin: 16.68 MiB / 16.68 MiB [=========================] 100.00% 1s
Downloading plugin: 97.99 MiB / 97.99 MiB [=========================] 100.00% 4s
     Type                 Name          Plan
 +   pulumi:pulumi:Stack  test-app-dev  create
 +   └─ aws:s3:Bucket     my-bucket     create

Resources:
    + 2 to create

```

Does your program perform plugin acquisition automatically? If not, is there a `node_modules` directory in your local directory?

**Comment by justinvp** [comment] 2023-07-18 23:00
Closing as No Repro. If you're still running into this, please open a new issue. Thanks!

**Closed by justinvp** 2023-07-18 23:00 UTC
Labels: kind/bug, resolution/no-repro
